namespace Model.Injuries
{
    public enum InjuryEnum
    {
        None,
        Abdominal_Cut,
        Broken_Arm,
        Broken_Jaw,
        Broken_Hand,
        Broken_Nose,
        Cut_Arm,
        Cut_Ear,
        Cut_Hand,
        Cut_Leg,
        Cut_Nose,
        Fractured_Ribs,
        Fractured_Skull,
        Major_Bleeding,
        Massive_Bleeding,
        Minor_Bleeding,
        Minor_Concussion,
        Pierced_Chest,
        Pierced_Guts,
        Pierced_Hand,
        Pierced_Lung,
        Pierced_Shoulder,
        Profuse_Bleeding,
        Rip,
        Severe_Concussion,
        Split_Hand,
        Tear,
        Torrential_Bleeding,
    }
}
