namespace Assets.Model.Event
{
    public enum ECombatEv
    {
        None,
        ApplyInjury,
        APMod,
        Buff,
        Casting,
        CharKilled,
        Debuff,
        DoT,
        EndTurn,
        HoT,
        ModifyHP,
        ModifyStam,
        NewRound,
        NewTurn,
        PathMove,
        PathTraversed,
        PerformAbility,
        Shapeshift,
        Shield,
        StaminaMod,
        Summon,
        TileMove,
        UndoShieldWall,
        UndoSpearWall,
    }
}
