namespace Assets.Model.Event
{
    public enum ECombatEv
    {
        None,
        ApplyInjury,
        APMod,
        Buff,
        Casting,
        CharKilled,
        Debuff,
        DoT,
        EndTurn,
        HoT,
        ModifyHP,
        ModifyStam,
        NewRound,
        PathMove,
        PathTraversed,
        PerformAbility,
        Shapeshift,
        Shield,
        Summon,
        TakingAction,
        TileMove,
        ZoneEnter,
        ZoneExit,
    }
}
