namespace Model.Abilities
{
    public enum WeaponAbilitiesEnum
    {
        None,
        Aim,
        Break_Armor,
        Break_Shield,
        Chop,
        Crush,
        Double_Strike,
        Fire,
        Gash,
        Great_Strike,
        Maim,
        Pierce,
        Pull,
        Riposte,
        Scatter,
        Shield_Wall,
        Shove,
        Slash,
        Spear_Wall,
        Stab,
        Stun,
        Triple_Strike,
        Wide_Slash,
        Wrap,
    }
}
