namespace Model.Perks
{
    public enum PerkEnum
    {
        None,
        Barbarism,
        Bash_Buddy,
        Bastion,
        Colossus,
        Dino_Bite,
        Enrage,
        Executioner,
        Gargantuan,
        Hulk,
        Iron_Hide,
        Massive,
        Medium_Shield_Expert,
        Predator,
        Savage_Soul,
        Savage_Visage,
        Scaly,
        Shield_Happy,
        Shield_Pro,
        Small_Shield_Expert,
        Squishy,
        Weightlifter,
        Violence_Fetish,
        T_Rex_Bite,
    }
}
