namespace Assets.Model.Perk
{
    public enum EPerk
    {
        None,
        Barbarism,
        Bash_Buddy,
        Bastion,
        Bully,
        Colossus,
        Enrage,
        Executioner,
        Gargantuan,
        Hulk,
        Iron_Hide,
        Massive,
        Medium_Shield_Expert,
        Predator,
        Savage_Soul,
        Savage_Visage,
        Scaly,
        Shield_Brother,
        Shield_Happy,
        Shield_Pro,
        Small_Shield_Expert,
        Squishy,
        Weightlifter,
        Violence_Fetish,
        Two_Handed_Expert,
    }
}
